sudo: required
services:
    - docker

before_install:
    - docker build -t sunandnair/dock-r -f Dockerfile.dev .

script:
    - docker run -e CI=true sunandnair/dock-r npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "dockr"
    env: "Dockr-env"
    bucket_name: "elasticbeanstalk-eu-west-2-541037095374"
    bucket_path: "dockr"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"